// <auto-generated />
using DevPace.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevPace.EntityFramework.Migrations
{
    [DbContext(typeof(DevPaceDbContext))]
    partial class DevPaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevPace.Domain.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyName = "Company 1",
                            Email = "email1@mail.com",
                            Name = "Name 1",
                            Phone = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CompanyName = "Company 2",
                            Email = "email2@mail.com",
                            Name = "Name 2",
                            Phone = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CompanyName = "Company 3",
                            Email = "email3@mail.com",
                            Name = "Name 3",
                            Phone = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CompanyName = "Company 4",
                            Email = "email4@mail.com",
                            Name = "Name 4",
                            Phone = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CompanyName = "Company 5",
                            Email = "email5@mail.com",
                            Name = "Name 5",
                            Phone = "5"
                        },
                        new
                        {
                            Id = 6L,
                            CompanyName = "Company 6",
                            Email = "email6@mail.com",
                            Name = "Name 6",
                            Phone = "6"
                        },
                        new
                        {
                            Id = 7L,
                            CompanyName = "Company 7",
                            Email = "email7@mail.com",
                            Name = "Name 7",
                            Phone = "7"
                        },
                        new
                        {
                            Id = 8L,
                            CompanyName = "Company 8",
                            Email = "email8@mail.com",
                            Name = "Name 8",
                            Phone = "8"
                        },
                        new
                        {
                            Id = 9L,
                            CompanyName = "Company 9",
                            Email = "email9@mail.com",
                            Name = "Name 9",
                            Phone = "9"
                        },
                        new
                        {
                            Id = 10L,
                            CompanyName = "Company 10",
                            Email = "email10@mail.com",
                            Name = "Name 10",
                            Phone = "10"
                        },
                        new
                        {
                            Id = 11L,
                            CompanyName = "Company 11",
                            Email = "email11@mail.com",
                            Name = "Name 11",
                            Phone = "11"
                        },
                        new
                        {
                            Id = 12L,
                            CompanyName = "Company 12",
                            Email = "email12@mail.com",
                            Name = "Name 12",
                            Phone = "12"
                        },
                        new
                        {
                            Id = 13L,
                            CompanyName = "Company 13",
                            Email = "email13@mail.com",
                            Name = "Name 13",
                            Phone = "13"
                        },
                        new
                        {
                            Id = 14L,
                            CompanyName = "Company 14",
                            Email = "email14@mail.com",
                            Name = "Name 14",
                            Phone = "14"
                        },
                        new
                        {
                            Id = 15L,
                            CompanyName = "Company 15",
                            Email = "email15@mail.com",
                            Name = "Name 15",
                            Phone = "15"
                        },
                        new
                        {
                            Id = 16L,
                            CompanyName = "Company 16",
                            Email = "email16@mail.com",
                            Name = "Name 16",
                            Phone = "16"
                        },
                        new
                        {
                            Id = 17L,
                            CompanyName = "Company 17",
                            Email = "email17@mail.com",
                            Name = "Name 17",
                            Phone = "17"
                        },
                        new
                        {
                            Id = 18L,
                            CompanyName = "Company 18",
                            Email = "email18@mail.com",
                            Name = "Name 18",
                            Phone = "18"
                        },
                        new
                        {
                            Id = 19L,
                            CompanyName = "Company 19",
                            Email = "email19@mail.com",
                            Name = "Name 19",
                            Phone = "19"
                        },
                        new
                        {
                            Id = 20L,
                            CompanyName = "Company 20",
                            Email = "email20@mail.com",
                            Name = "Name 20",
                            Phone = "20"
                        },
                        new
                        {
                            Id = 21L,
                            CompanyName = "Company 21",
                            Email = "email21@mail.com",
                            Name = "Name 21",
                            Phone = "21"
                        },
                        new
                        {
                            Id = 22L,
                            CompanyName = "Company 22",
                            Email = "email22@mail.com",
                            Name = "Name 22",
                            Phone = "22"
                        },
                        new
                        {
                            Id = 23L,
                            CompanyName = "Company 23",
                            Email = "email23@mail.com",
                            Name = "Name 23",
                            Phone = "23"
                        },
                        new
                        {
                            Id = 24L,
                            CompanyName = "Company 24",
                            Email = "email24@mail.com",
                            Name = "Name 24",
                            Phone = "24"
                        },
                        new
                        {
                            Id = 25L,
                            CompanyName = "Company 25",
                            Email = "email25@mail.com",
                            Name = "Name 25",
                            Phone = "25"
                        },
                        new
                        {
                            Id = 26L,
                            CompanyName = "Company 26",
                            Email = "email26@mail.com",
                            Name = "Name 26",
                            Phone = "26"
                        },
                        new
                        {
                            Id = 27L,
                            CompanyName = "Company 27",
                            Email = "email27@mail.com",
                            Name = "Name 27",
                            Phone = "27"
                        },
                        new
                        {
                            Id = 28L,
                            CompanyName = "Company 28",
                            Email = "email28@mail.com",
                            Name = "Name 28",
                            Phone = "28"
                        },
                        new
                        {
                            Id = 29L,
                            CompanyName = "Company 29",
                            Email = "email29@mail.com",
                            Name = "Name 29",
                            Phone = "29"
                        },
                        new
                        {
                            Id = 30L,
                            CompanyName = "Company 30",
                            Email = "email30@mail.com",
                            Name = "Name 30",
                            Phone = "30"
                        },
                        new
                        {
                            Id = 31L,
                            CompanyName = "Company 31",
                            Email = "email31@mail.com",
                            Name = "Name 31",
                            Phone = "31"
                        },
                        new
                        {
                            Id = 32L,
                            CompanyName = "Company 32",
                            Email = "email32@mail.com",
                            Name = "Name 32",
                            Phone = "32"
                        },
                        new
                        {
                            Id = 33L,
                            CompanyName = "Company 33",
                            Email = "email33@mail.com",
                            Name = "Name 33",
                            Phone = "33"
                        },
                        new
                        {
                            Id = 34L,
                            CompanyName = "Company 34",
                            Email = "email34@mail.com",
                            Name = "Name 34",
                            Phone = "34"
                        },
                        new
                        {
                            Id = 35L,
                            CompanyName = "Company 35",
                            Email = "email35@mail.com",
                            Name = "Name 35",
                            Phone = "35"
                        },
                        new
                        {
                            Id = 36L,
                            CompanyName = "Company 36",
                            Email = "email36@mail.com",
                            Name = "Name 36",
                            Phone = "36"
                        },
                        new
                        {
                            Id = 37L,
                            CompanyName = "Company 37",
                            Email = "email37@mail.com",
                            Name = "Name 37",
                            Phone = "37"
                        },
                        new
                        {
                            Id = 38L,
                            CompanyName = "Company 38",
                            Email = "email38@mail.com",
                            Name = "Name 38",
                            Phone = "38"
                        },
                        new
                        {
                            Id = 39L,
                            CompanyName = "Company 39",
                            Email = "email39@mail.com",
                            Name = "Name 39",
                            Phone = "39"
                        },
                        new
                        {
                            Id = 40L,
                            CompanyName = "Company 40",
                            Email = "email40@mail.com",
                            Name = "Name 40",
                            Phone = "40"
                        },
                        new
                        {
                            Id = 41L,
                            CompanyName = "Company 41",
                            Email = "email41@mail.com",
                            Name = "Name 41",
                            Phone = "41"
                        },
                        new
                        {
                            Id = 42L,
                            CompanyName = "Company 42",
                            Email = "email42@mail.com",
                            Name = "Name 42",
                            Phone = "42"
                        },
                        new
                        {
                            Id = 43L,
                            CompanyName = "Company 43",
                            Email = "email43@mail.com",
                            Name = "Name 43",
                            Phone = "43"
                        },
                        new
                        {
                            Id = 44L,
                            CompanyName = "Company 44",
                            Email = "email44@mail.com",
                            Name = "Name 44",
                            Phone = "44"
                        },
                        new
                        {
                            Id = 45L,
                            CompanyName = "Company 45",
                            Email = "email45@mail.com",
                            Name = "Name 45",
                            Phone = "45"
                        },
                        new
                        {
                            Id = 46L,
                            CompanyName = "Company 46",
                            Email = "email46@mail.com",
                            Name = "Name 46",
                            Phone = "46"
                        },
                        new
                        {
                            Id = 47L,
                            CompanyName = "Company 47",
                            Email = "email47@mail.com",
                            Name = "Name 47",
                            Phone = "47"
                        },
                        new
                        {
                            Id = 48L,
                            CompanyName = "Company 48",
                            Email = "email48@mail.com",
                            Name = "Name 48",
                            Phone = "48"
                        },
                        new
                        {
                            Id = 49L,
                            CompanyName = "Company 49",
                            Email = "email49@mail.com",
                            Name = "Name 49",
                            Phone = "49"
                        },
                        new
                        {
                            Id = 50L,
                            CompanyName = "Company 50",
                            Email = "email50@mail.com",
                            Name = "Name 50",
                            Phone = "50"
                        },
                        new
                        {
                            Id = 51L,
                            CompanyName = "Company 51",
                            Email = "email51@mail.com",
                            Name = "Name 51",
                            Phone = "51"
                        },
                        new
                        {
                            Id = 52L,
                            CompanyName = "Company 52",
                            Email = "email52@mail.com",
                            Name = "Name 52",
                            Phone = "52"
                        },
                        new
                        {
                            Id = 53L,
                            CompanyName = "Company 53",
                            Email = "email53@mail.com",
                            Name = "Name 53",
                            Phone = "53"
                        },
                        new
                        {
                            Id = 54L,
                            CompanyName = "Company 54",
                            Email = "email54@mail.com",
                            Name = "Name 54",
                            Phone = "54"
                        },
                        new
                        {
                            Id = 55L,
                            CompanyName = "Company 55",
                            Email = "email55@mail.com",
                            Name = "Name 55",
                            Phone = "55"
                        },
                        new
                        {
                            Id = 56L,
                            CompanyName = "Company 56",
                            Email = "email56@mail.com",
                            Name = "Name 56",
                            Phone = "56"
                        },
                        new
                        {
                            Id = 57L,
                            CompanyName = "Company 57",
                            Email = "email57@mail.com",
                            Name = "Name 57",
                            Phone = "57"
                        },
                        new
                        {
                            Id = 58L,
                            CompanyName = "Company 58",
                            Email = "email58@mail.com",
                            Name = "Name 58",
                            Phone = "58"
                        },
                        new
                        {
                            Id = 59L,
                            CompanyName = "Company 59",
                            Email = "email59@mail.com",
                            Name = "Name 59",
                            Phone = "59"
                        },
                        new
                        {
                            Id = 60L,
                            CompanyName = "Company 60",
                            Email = "email60@mail.com",
                            Name = "Name 60",
                            Phone = "60"
                        },
                        new
                        {
                            Id = 61L,
                            CompanyName = "Company 61",
                            Email = "email61@mail.com",
                            Name = "Name 61",
                            Phone = "61"
                        },
                        new
                        {
                            Id = 62L,
                            CompanyName = "Company 62",
                            Email = "email62@mail.com",
                            Name = "Name 62",
                            Phone = "62"
                        },
                        new
                        {
                            Id = 63L,
                            CompanyName = "Company 63",
                            Email = "email63@mail.com",
                            Name = "Name 63",
                            Phone = "63"
                        },
                        new
                        {
                            Id = 64L,
                            CompanyName = "Company 64",
                            Email = "email64@mail.com",
                            Name = "Name 64",
                            Phone = "64"
                        },
                        new
                        {
                            Id = 65L,
                            CompanyName = "Company 65",
                            Email = "email65@mail.com",
                            Name = "Name 65",
                            Phone = "65"
                        },
                        new
                        {
                            Id = 66L,
                            CompanyName = "Company 66",
                            Email = "email66@mail.com",
                            Name = "Name 66",
                            Phone = "66"
                        },
                        new
                        {
                            Id = 67L,
                            CompanyName = "Company 67",
                            Email = "email67@mail.com",
                            Name = "Name 67",
                            Phone = "67"
                        },
                        new
                        {
                            Id = 68L,
                            CompanyName = "Company 68",
                            Email = "email68@mail.com",
                            Name = "Name 68",
                            Phone = "68"
                        },
                        new
                        {
                            Id = 69L,
                            CompanyName = "Company 69",
                            Email = "email69@mail.com",
                            Name = "Name 69",
                            Phone = "69"
                        },
                        new
                        {
                            Id = 70L,
                            CompanyName = "Company 70",
                            Email = "email70@mail.com",
                            Name = "Name 70",
                            Phone = "70"
                        },
                        new
                        {
                            Id = 71L,
                            CompanyName = "Company 71",
                            Email = "email71@mail.com",
                            Name = "Name 71",
                            Phone = "71"
                        },
                        new
                        {
                            Id = 72L,
                            CompanyName = "Company 72",
                            Email = "email72@mail.com",
                            Name = "Name 72",
                            Phone = "72"
                        },
                        new
                        {
                            Id = 73L,
                            CompanyName = "Company 73",
                            Email = "email73@mail.com",
                            Name = "Name 73",
                            Phone = "73"
                        },
                        new
                        {
                            Id = 74L,
                            CompanyName = "Company 74",
                            Email = "email74@mail.com",
                            Name = "Name 74",
                            Phone = "74"
                        },
                        new
                        {
                            Id = 75L,
                            CompanyName = "Company 75",
                            Email = "email75@mail.com",
                            Name = "Name 75",
                            Phone = "75"
                        },
                        new
                        {
                            Id = 76L,
                            CompanyName = "Company 76",
                            Email = "email76@mail.com",
                            Name = "Name 76",
                            Phone = "76"
                        },
                        new
                        {
                            Id = 77L,
                            CompanyName = "Company 77",
                            Email = "email77@mail.com",
                            Name = "Name 77",
                            Phone = "77"
                        },
                        new
                        {
                            Id = 78L,
                            CompanyName = "Company 78",
                            Email = "email78@mail.com",
                            Name = "Name 78",
                            Phone = "78"
                        },
                        new
                        {
                            Id = 79L,
                            CompanyName = "Company 79",
                            Email = "email79@mail.com",
                            Name = "Name 79",
                            Phone = "79"
                        },
                        new
                        {
                            Id = 80L,
                            CompanyName = "Company 80",
                            Email = "email80@mail.com",
                            Name = "Name 80",
                            Phone = "80"
                        },
                        new
                        {
                            Id = 81L,
                            CompanyName = "Company 81",
                            Email = "email81@mail.com",
                            Name = "Name 81",
                            Phone = "81"
                        },
                        new
                        {
                            Id = 82L,
                            CompanyName = "Company 82",
                            Email = "email82@mail.com",
                            Name = "Name 82",
                            Phone = "82"
                        },
                        new
                        {
                            Id = 83L,
                            CompanyName = "Company 83",
                            Email = "email83@mail.com",
                            Name = "Name 83",
                            Phone = "83"
                        },
                        new
                        {
                            Id = 84L,
                            CompanyName = "Company 84",
                            Email = "email84@mail.com",
                            Name = "Name 84",
                            Phone = "84"
                        },
                        new
                        {
                            Id = 85L,
                            CompanyName = "Company 85",
                            Email = "email85@mail.com",
                            Name = "Name 85",
                            Phone = "85"
                        },
                        new
                        {
                            Id = 86L,
                            CompanyName = "Company 86",
                            Email = "email86@mail.com",
                            Name = "Name 86",
                            Phone = "86"
                        },
                        new
                        {
                            Id = 87L,
                            CompanyName = "Company 87",
                            Email = "email87@mail.com",
                            Name = "Name 87",
                            Phone = "87"
                        },
                        new
                        {
                            Id = 88L,
                            CompanyName = "Company 88",
                            Email = "email88@mail.com",
                            Name = "Name 88",
                            Phone = "88"
                        },
                        new
                        {
                            Id = 89L,
                            CompanyName = "Company 89",
                            Email = "email89@mail.com",
                            Name = "Name 89",
                            Phone = "89"
                        },
                        new
                        {
                            Id = 90L,
                            CompanyName = "Company 90",
                            Email = "email90@mail.com",
                            Name = "Name 90",
                            Phone = "90"
                        },
                        new
                        {
                            Id = 91L,
                            CompanyName = "Company 91",
                            Email = "email91@mail.com",
                            Name = "Name 91",
                            Phone = "91"
                        },
                        new
                        {
                            Id = 92L,
                            CompanyName = "Company 92",
                            Email = "email92@mail.com",
                            Name = "Name 92",
                            Phone = "92"
                        },
                        new
                        {
                            Id = 93L,
                            CompanyName = "Company 93",
                            Email = "email93@mail.com",
                            Name = "Name 93",
                            Phone = "93"
                        },
                        new
                        {
                            Id = 94L,
                            CompanyName = "Company 94",
                            Email = "email94@mail.com",
                            Name = "Name 94",
                            Phone = "94"
                        },
                        new
                        {
                            Id = 95L,
                            CompanyName = "Company 95",
                            Email = "email95@mail.com",
                            Name = "Name 95",
                            Phone = "95"
                        },
                        new
                        {
                            Id = 96L,
                            CompanyName = "Company 96",
                            Email = "email96@mail.com",
                            Name = "Name 96",
                            Phone = "96"
                        },
                        new
                        {
                            Id = 97L,
                            CompanyName = "Company 97",
                            Email = "email97@mail.com",
                            Name = "Name 97",
                            Phone = "97"
                        },
                        new
                        {
                            Id = 98L,
                            CompanyName = "Company 98",
                            Email = "email98@mail.com",
                            Name = "Name 98",
                            Phone = "98"
                        },
                        new
                        {
                            Id = 99L,
                            CompanyName = "Company 99",
                            Email = "email99@mail.com",
                            Name = "Name 99",
                            Phone = "99"
                        },
                        new
                        {
                            Id = 100L,
                            CompanyName = "Company 100",
                            Email = "email100@mail.com",
                            Name = "Name 100",
                            Phone = "100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
